language: php
php:
  - '5.4'
  - '5.5'
  - '5.5.9'
  - '5.6'
  - '7.0'
  - hhvm
matrix:
  allow_failures:
    - php: '5.4'
    - php: '7.0'
    - php: hhvm
install:
  - echo 'error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install --ignore-platform-reqs
script:
  - php vendor/bin/behat --config=.travis-behat.yml
  - php vendor/bin/phpspec run -v --config=.travis-phpspec.yml
